"""Build the page.
  python3 src/build.py            -> api/_page.js  (no payroll data; served by api/app.js after sign-in)
  python3 src/build.py --offline  -> private/NIET_Payroll_offline.html (templates embedded; keep private)
Templates are read from private/ (git-ignored)."""
import base64, pathlib, sys
S = pathlib.Path(__file__).parent; R = S.parent
h = (S / 'app.src.html').read_text()
h = h.replace('/*JSZIP*/', (S / 'jszip.min.js').read_text().replace('</script', '<\\/script'), 1)
h = h.replace('/*ENGINE*/', (S / 'engine.js').read_text(), 1)
h = h.replace('/*PIENGINE*/', (R / 'pi' / 'pi-engine.js').read_text(), 1)
h = h.replace('/*TRVENGINE*/', (R / 'travel' / 'travel-engine.js').read_text(), 1)
h = h.replace('/*TRVTPL*/', base64.b64encode((R / 'travel' / 'travel_template.xlsx').read_bytes()).decode(), 1)
h = h.replace('/*PITPL*/', base64.b64encode((R / 'pi' / 'pi_template.xlsx').read_bytes()).decode(), 1)
for k in ('64', '32'):
    h = h.replace('/*ICON' + k + '*/', base64.b64encode((S / f'icon-{k}.png').read_bytes()).decode())
if '--offline' in sys.argv:
    P = R / 'private'
    h = h.replace('/*XLSX_B64*/', base64.b64encode((P / 'payroll_template.xlsx').read_bytes()).decode())
    h = h.replace('/*DOCX_B64*/', base64.b64encode((P / 'memo_template.docx').read_bytes()).decode())
    out = R / 'private' / 'NIET_Payroll_offline.html'
else:
    import json
    out = R / 'api' / '_page.js'
    h = '// Generated by src/build.py. Do not edit.\nexport default ' + json.dumps(h) + ';\n'
out.write_text(h)
print(out.relative_to(R), len(h), 'bytes')
