// Encrypts private/payroll_template.xlsx + private/memo_template.docx into api/_sealed.js
// with AES-256-GCM, so the public repo carries only ciphertext.
//   node src/seal.mjs        (reads the key from private/TEMPLATE_KEY.txt, 64 hex chars)
import fs from 'node:fs'; import crypto from 'node:crypto';
const R = new URL('..', import.meta.url).pathname;
const key = Buffer.from(fs.readFileSync(R + 'private/TEMPLATE_KEY.txt', 'utf8').trim(), 'hex');
if (key.length !== 32) throw new Error('TEMPLATE_KEY must be 64 hex characters');
const xlsx = fs.readFileSync(R + 'private/payroll_template.xlsx'), docx = fs.readFileSync(R + 'private/memo_template.docx');
const plain = Buffer.from(JSON.stringify({ xlsx: xlsx.toString('base64'), docx: docx.toString('base64') }));
const iv = crypto.randomBytes(12);
const c = crypto.createCipheriv('aes-256-gcm', key, iv);
const ct = Buffer.concat([c.update(plain), c.final()]);
const version = crypto.createHash('sha256').update(Buffer.concat([xlsx, docx])).digest('hex').slice(0, 6).toUpperCase();
const sealed = { v: 1, version, iv: iv.toString('base64'), tag: c.getAuthTag().toString('base64'), ct: ct.toString('base64') };
fs.writeFileSync(R + 'api/_sealed.js', '// Generated by src/seal.mjs. Encrypted templates (AES-256-GCM). Do not edit.\nexport default ' + JSON.stringify(sealed) + ';\n');
console.log('sealed templates, version', version);
